services:
  postgresql:
    image: docker.io/bitnami/postgresql:17
    ports:
      - '5432:5432'
    volumes:
      - 'postgresql_data:/bitnami/postgresql'
    environment:
      - 'POSTGRESQL_USERNAME=docker'
      - 'POSTGRESQL_PASSWORD=docker'
      - 'POSTGRESQL_DATABASE=gym-api'

volumes:
  postgresql_data:
    driver: local